/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type Subtitle = string;
export type DocumentDescription = string;
export type Description = string;
export type Locale = string;
export type DueDate = string;
export type EndDate = string;
export type Authors = string;
export type UpdatedDate = string;
export type ModelVersion = string;
export type Stats = string;
export type ManDaysDistribution = string;
export type TotalManDays = string;
export type RevisionTable = string;
export type Date = string;
export type Version = string;
export type Sections = string;
export type Comment = string;
export type TableOfContent = string;
export type Organigram = string;
export type DeliverableMap = string;
export type UserStories = string;
export type AsUser = string;
export type UserWant = string;
export type DefinitionOfDone = string;
export type Assignation = string;
export type EstimatedDuration = string;
export type ManDays = string;
export type Hours = string;
export type Status = string;
export type Comments = string;
export type AdvancementReport = string;
export type ToDo = string;
export type Wip = string;
export type Done = string;
export type Abandoned = string;
export type ProjectLogDocument = string;
export type Page = string;
export type Of = string;

export interface LocaleDictionary {
  title: Title;
  subtitle: Subtitle;
  document_description: DocumentDescription;
  description: Description;
  locale: Locale;
  due_date: DueDate;
  end_date: EndDate;
  authors: Authors;
  updated_date: UpdatedDate;
  model_version: ModelVersion;
  stats: Stats;
  man_days_distribution: ManDaysDistribution;
  total_man_days: TotalManDays;
  revision_table: RevisionTable;
  date: Date;
  version: Version;
  sections: Sections;
  comment: Comment;
  table_of_content: TableOfContent;
  organigram: Organigram;
  deliverable_map: DeliverableMap;
  user_stories: UserStories;
  as_user: AsUser;
  user_want: UserWant;
  definition_of_done: DefinitionOfDone;
  assignation: Assignation;
  estimated_duration: EstimatedDuration;
  man_days: ManDays;
  hours: Hours;
  status: Status;
  comments: Comments;
  advancement_report: AdvancementReport;
  to_do: ToDo;
  wip: Wip;
  done: Done;
  abandoned: Abandoned;
  project_log_document: ProjectLogDocument;
  page: Page;
  of: Of;
  [k: string]: unknown;
}
