/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Locale of the PLD
 */
export type Locale = Locale1 | string;
/**
 * An enumeration.
 */
export type Locale1 = "fr_FR";
/**
 * Main title on document title page
 */
export type Title = string;
/**
 * Subtitle on document title page
 */
export type Subtitle = string;
/**
 * Description of document
 */
export type Description = string;
/**
 * List of document authors
 */
export type Authors = string[];
export type Version1 = string;
/**
 * Release date of this version
 */
export type Date = string;
/**
 * Authors of this version
 */
export type Authors1 = string[];
/**
 * Which sections have been modified
 */
export type Sections = string;
/**
 * Comment about this version
 */
export type Comment = string;
export type Versions = Version[];
export type Type = "deliverable";
export type Name = string;
export type Description1 = string;
export type Type1 = "subset";
export type Name1 = string;
export type Description2 = string;
export type Type2 = "user_story";
/**
 * Name of the user story
 */
export type Name2 = string;
/**
 * User that do the action of user story
 */
export type User = string;
/**
 * Action done by the user
 */
export type Action = string;
/**
 * Detailed description of the user
 */
export type Description3 = string;
/**
 * List of definition of done (list of goal) that must be done to complete the user story
 */
export type DefinitionsOfDone = string[];
/**
 * Number of estimated man day (8 hours)
 */
export type EstimatedDuration = number;
/**
 * User story due date
 */
export type DueDate = string;
/**
 * Date when the user story was marked as Done
 */
export type EndDate = string;
/**
 * An enumeration.
 */
export type Status = "To do" | "WIP" | "Done" | "Abandoned";
/**
 * List of person assigned to work on this user story
 */
export type Assignments = string[];
/**
 * Comment about the user story
 */
export type Comments = string[] | string;
export type UserStories = UserStory[];
/**
 * Subset that groups many user story
 */
export type Subsets = Subset[];
/**
 * Project deliverable
 */
export type Deliverables = Deliverable[];

export interface PLDSchema {
  locale: Locale;
  title: Title;
  subtitle?: Subtitle;
  description?: Description;
  authors?: Authors;
  versions?: Versions;
  deliverables?: Deliverables;
  [k: string]: unknown;
}
export interface Version {
  version: Version1;
  date: Date;
  authors?: Authors1;
  sections: Sections;
  comment: Comment;
  [k: string]: unknown;
}
export interface Deliverable {
  type?: Type;
  name: Name;
  description?: Description1;
  subsets?: Subsets;
  [k: string]: unknown;
}
export interface Subset {
  type?: Type1;
  name: Name1;
  description?: Description2;
  user_stories?: UserStories;
  [k: string]: unknown;
}
export interface UserStory {
  type?: Type2;
  name: Name2;
  user: User;
  action: Action;
  description?: Description3;
  definitions_of_done?: DefinitionsOfDone;
  estimated_duration: EstimatedDuration;
  due_date?: DueDate;
  end_date?: EndDate;
  /**
   * User story work status
   */
  status?: Status & string;
  assignments?: Assignments;
  comments?: Comments;
  [k: string]: unknown;
}
